version: "3.9"

services:
  main-app: # service name
    build:
      context: . # current directory
      args: # arguments
        - DEV=true # overwrite arg DEV. DEV=true indicates that it is in development environment not in production one
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment: # this environment var are used in code
      - DB_HOST=db # db is service's name for database
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db # service main-app depends on service db

  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb # this env name is based on postgres image on docker hub
      - POSTGRES_USER=devuser # this env name is based on postgres image on docker hub
      - POSTGRES_PASSWORD=changeme # this env name is based on postgres image on docker hub

volumes:
  dev-db-data:
  dev-static-data: